name: Python for Embed Release Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

env:
  latest_version: '3.14'

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        arch: ['x86', 'x64']

    steps:
      - name: Get version
        run: |
          $json = Invoke-RestMethod -Uri https://github.com/docker-library/python/raw/refs/heads/master/versions.json
          $version = $json."${{ matrix.version }}".version
          if (-not $version) {
            Write-Error "Version is empty or null. Exiting."
            exit 1
          }
          Write-Output "version=$version" >> $env:GITHUB_ENV
          Write-Output "tag=v$version" >> $env:GITHUB_ENV
          Write-Output "Current version is $version"

      - name: Check Release
        run: |
          if ! gh release view ${{ env.version }} -R ${{ github.repository }} > /dev/null 2>&1; then
            echo "Release ${{ env.version }} does not exist. Continuing with the build."
            echo "build=1" >> $GITHUB_ENV
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        if: env.build == '1'
        uses: actions/checkout@v6
        with:
          path: main

      - name: Checkout CPython
        if: env.build == '1'
        uses: actions/checkout@v6
        with:
          repository: python/cpython
          ref: ${{ env.tag }}
          path: cpython

      - name: Reset Config
        if: env.build == '1'
        run: |
          sed -i 's@ --dirty@@g' PCbuild/pythoncore.vcxproj
          sed -i 's@--precompile@--precompile --include-pip --include-tcltk@g' Tools/msi/make_zip.proj
          cat Tools/msi/make_zip.proj | grep 'stable'
        shell: bash
        working-directory: cpython

      - name: Create embed layout
        if: env.build == '1'
        run: |
          Tools\\msi\\buildrelease.bat -${{ matrix.arch }} --skip-doc --skip-pgo --skip-msi --skip-nuget
        working-directory: cpython

      - name: Move embed layout
        if: env.build == '1'
        run: |
          $arch = '${{ matrix.arch }}'
          $source = switch ($arch) {
            'x64' { 'cpython\PCbuild\amd64\en-us' }
            'x86' { 'cpython\PCbuild\win32\en-us' }
            'arm64' { 'cpython\PCbuild\arm64\en-us' }
          }
          $destination = 'main\dist'
          Move-Item -Path $source -Destination $destination -Force

      - name: Create Tag
        if: env.build == '1'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ env.version }} -m "Release Version ${{ env.version }}" || true
          git push origin ${{ env.version }} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: main

      - name: Create Release
        if: env.build == '1'
        run: |
          latestFlag=""
          if [ "${{ matrix.version }}" != "${{ env.latest_version }}" ]; then
            latestFlag="--latest=false"
          fi
          gh release create ${{ env.version }} -R ${{ github.repository}} --notes "Python for Stable Release ${{ env.version }}" $latestFlag || true
          gh release upload ${{ env.version }} -R ${{ github.repository}} dist/*.zip || true
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: main